/*
 * Choreografy API

 package x/openapi is not in GOROOT (/home/atu045/go/go/src/x/openapi)go

 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package main

import "github.com/adeturner/persistenceServices"

func main() {
	persistenceServices.LocalEntry()
}
